name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Deploy code and run tasks on server
      run: |
        ssh -o StrictHostKeyChecking=yes ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        echo "Current directory: $(pwd)"
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
        cd ${{ secrets.LARAVEL_APP_PATH }}
        git pull origin main
        composer install --no-dev
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        npm install
        npm run build
        ./run.sh
        EOF
